// <auto-generated />
using System;
using Farmasia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farmasia.Migrations
{
    [DbContext(typeof(FarmasiaContext))]
    [Migration("20220702104230_AlterSProduit")]
    partial class AlterSProduit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Farmasia.Models.Produit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("Farmasia.Models.SProduit", b =>
                {
                    b.Property<string>("SProduitID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Design")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PU")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QTE")
                        .HasColumnType("int");

                    b.Property<string>("SProduitIDa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SProduitID");

                    b.ToTable("SProduit");
                });
#pragma warning restore 612, 618
        }
    }
}
